version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=urlshortener
      - DB_PASSWORD=urlshortener123
      - DB_NAME=urlshortener
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_SECRET=super-secret-access-urlshortener
      - JWT_REFRESH_SECRET=super-secret-refresh-urlshortener
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-flash-lite-latest
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      - postgres
      - redis
      - jaeger

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener123
      POSTGRES_DB: urlshortener
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

  jaeger:
    image: jaegertracing/all-in-one:1.55
    restart: always
    ports:
      - '16686:16686'
      - '4318:4318'

volumes:
  postgres_data:
